import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
import assert from 'node:assert/strict';
const bundle = await build({ entryPoints:['src/main.jsx'],bundle:true,write:false,format:'iife',loader:{'.css':'empty'},define:{'process.env.NODE_ENV':'"production"'} });
const dom = new JSDOM('<div id="root"></div>',{url:'http://localhost/#/build',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window; w.scrollTo=()=>{}; w.HTMLElement.prototype.scrollIntoView=()=>{};
const errors=[]; w.addEventListener('error',e=>errors.push(e.message));
w.eval(bundle.outputFiles[0].text);
const settle=()=>new Promise(r=>setTimeout(r,65));
await settle();
const click=async(text)=>{const el=[...w.document.querySelectorAll('button,a')].find(e=>e.textContent.includes(text));assert.ok(el,`Missing ${text}`);el.click();await settle();};
w.document.querySelector('[aria-label="Add a traveler"]').click();await settle();
await click('Next: your stay'); await click('Right in the middle');
assert.match(w.document.body.textContent,/walk from your Monaco base/);
await click('Next: your view'); await click('Grandstand K'); await click('Next: little extras'); await click('Add to my trip');
assert.equal(JSON.parse(w.localStorage.getItem('guideless-trip')).boatGuests,1);
await click('Next: review');
assert.match(w.document.querySelector('.summary-total').textContent,/14,470/);
await click('Preview my trip app');
assert.match(w.document.querySelector('.app-next-card').textContent,/scenic route/);
w.document.querySelector('[aria-label="View traveler profile"]').click();await settle();
const guest=w.document.querySelector('#active-guest');guest.value='2';guest.dispatchEvent(new w.Event('change',{bubbles:true}));await settle();
w.document.querySelector('[aria-label="Close dialog"]').click();await settle();
assert.match(w.document.querySelector('.app-next-card').textContent,/slow start/);
await click('My trip');assert.match(w.document.querySelector('.app-view').textContent,/Walk to the circuit/);
await click('My tickets');assert.ok(w.document.querySelector('[role="dialog"]'));
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await settle();
assert.equal(w.document.querySelector('[role="dialog"]'),null);
await click('People');await click('You’re interested');assert.match(w.document.querySelector('.group-event').textContent,/Count me in/);
assert.deepEqual(errors,[]);console.log('React flow passed: two travelers, Monaco upgrade, pricing, partial-group activity, synced app, tickets, dialog dismissal, RSVP.');
w.close();
