import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowLeft, ArrowDown, Check, ChevronDown, ChevronRight, ChevronLeft, Menu, X, MapPin, CalendarDays, Users, TrainFront, BedDouble, Coffee, Sparkles, Plus, Minus, Clock3, Heart, ShieldCheck, CheckCheck, Flag, Ship, CarFront, Ticket, Sun, MessageCircle, Navigation, Map, Compass, Smartphone, Copy, Mail, ExternalLink, Luggage, Info, CircleCheck, CreditCard, Globe2 } from 'lucide-react';
import './styles.css';
import Approach from './Approach.jsx';

const ASSETS = {
  hero: '/images/monaco-panorama.jpg',
  nice: '/images/nice-real.jpg',
  monaco: '/images/monaco-panorama.jpg',
  france: '/images/france.jpg',
  boat: '/images/boat-real.jpg',
};
const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const initialTrip = { travelers: 1, stay: 'nice', race: 'grandstand', boat: false, boatGuests: 1, transfer: false };
function loadTrip() { try { const saved = JSON.parse(localStorage.getItem('guideless-trip') || '{}'); const travelers = Math.max(1, Math.min(4, Number(saved?.travelers) || 1)); return { ...initialTrip, travelers: Math.floor(travelers), stay: saved?.stay === 'monaco' ? 'monaco' : 'nice', race: ['none','grandstand','terrace','yacht'].includes(saved?.race) ? saved.race : 'grandstand', boat: saved?.boat === true, boatGuests: Math.max(1, Math.min(Math.floor(Number(saved?.boatGuests) || 1), Math.floor(travelers))), transfer: saved?.transfer === true }; } catch { return initialTrip; } }
function calculate(trip) {
  const base = 1890 * trip.travelers;
  const stay = (trip.stay === 'monaco' ? 3950 : 0) * trip.travelers;
  const race = ({ none: 0, grandstand: 1290, terrace: 3490, yacht: 5950 }[trip.race] || 0) * trip.travelers;
  const boat = trip.boat ? 210 * Math.min(trip.boatGuests, trip.travelers) : 0;
  const transfer = trip.transfer ? 120 : 0;
  return { base, stay, race, boat, transfer, total: base + stay + race + boat + transfer, today: 500 * trip.travelers + race + boat + transfer, later: base + stay - 500 * trip.travelers };
}
const raceNames = { none: 'Explore at your own pace', grandstand: 'Grandstand K', terrace: 'Harbour terrace', yacht: 'Harbour yacht' };

function Brand({ light = false, onClick, small = false }) {
  return <a className={`brand ${light ? 'light' : ''} ${small ? 'small' : ''}`} href="#/" onClick={onClick} aria-label="Guideless home"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M9 30V10h19M14 26 31 9M21 30h10V20" /></svg><span>guideless<span className="brand-dot">.</span></span></a>;
}
function Button({ children, onClick, href, secondary = false, className = '', ...props }) {
  const cls = `button ${secondary ? 'button-secondary' : 'button-primary'} ${className}`;
  return href ? <a className={cls} href={href} {...props}>{children}</a> : <button className={cls} onClick={onClick} {...props}>{children}</button>;
}
function Eyebrow({ children, light }) { return <div className={`eyebrow ${light ? 'on-dark' : ''}`}><span className="little-line" />{children}</div>; }
function Tag({ children, className = '' }) { return <span className={`tag ${className}`}>{children}</span>; }

function Header({ route, navigate }) {
  const [open, setOpen] = useState(false);
  useEffect(() => setOpen(false), [route]);
  return <header className="site-header"><div className="header-inner"><Brand onClick={() => setOpen(false)} /><nav className={`main-nav ${open ? 'nav-open' : ''}`} aria-label="Main navigation"><a href="#/#trips" onClick={(e) => { e.preventDefault(); navigate('/', 'trips'); setOpen(false); }}>Our trips <ChevronDown size={13} /></a><a href="#/#how-it-works" onClick={(e) => { e.preventDefault(); navigate('/', 'how-it-works'); setOpen(false); }}>How it works</a><a href="#/#our-story" onClick={(e) => { e.preventDefault(); navigate('/', 'our-story'); setOpen(false); }}>The Guideless way</a><a className="mobile-app-link" href="#/app">Your trip app <ArrowUpRight size={15} /></a></nav><div className="header-actions"><a className="concept-link" href="#/approach">Behind the design <ArrowUpRight size={14} /></a><a className="app-link" href="#/app"><Smartphone size={17} /> Your trip app</a><Button href="#/trip" className="header-cta">Find your next trip <ArrowUpRight size={16} /></Button><button className="menu-toggle icon-button" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></div></header>;
}

function Home({ navigate }) {
  return <>
    <main>
      <section className="hero wrap">
        <img className="hero-image" src={ASSETS.hero} alt="Monaco and its harbor on the French Riviera" fetchPriority="high" />
        <div className="hero-shade" />
        <div className="hero-content"><Eyebrow light>INDEPENDENT TRAVEL. BEAUTIFULLY SORTED.</Eyebrow><h1>A little structure.<br />A lot of <em>freedom.</em></h1><p>The stays. The journeys. The good company.<br />All taken care of. The rest is yours.</p><Button onClick={() => navigate('/', 'trips')} className="button-white">Find your kind of trip <ArrowUpRight size={19} /></Button><div className="hero-note"><span className="small-spark">✳</span> Go together. Do your own thing.</div></div>
        <a className="hero-location" href="#/trip"><span className="location-dot" /><span>YOUR NEXT CHAPTER<br /><strong>The French Riviera</strong></span><ArrowUpRight size={21} /></a>
        <div className="hero-bottom-index"><span>01 / RIVIERA</span><span className="hero-progress"><i /></span><span>EUROPE, ON YOUR TERMS</span></div>
      </section>
      <div className="promise-strip wrap"><span><BedDouble size={19} /> Lovely stays, already found</span><span><TrainFront size={19} /> The getting-there, handled</span><span><Users size={19} /> Good people, no headcounts</span><span><Compass size={19} /> Your days, your decisions</span></div>

      <section className="section wrap trips-section" id="trips"><div className="section-heading"><div><Eyebrow>GOOD PLACES. GREAT POSSIBILITIES.</Eyebrow><h2>Where to <em>next?</em></h2></div><p>A few places we know well.<br />A thousand ways to make them yours.</p></div><div className="trip-grid">
        <a className="trip-card trip-card-large" href="#/trip"><div className="trip-image"><img src={ASSETS.monaco} alt="Monaco's harbor and Mediterranean waterfront" loading="lazy" /><Tag className="image-tag"><Flag size={12} /> THE EVENT EDIT</Tag><span className="round-arrow"><ArrowUpRight size={22} /></span><div className="image-bottom"><span><CalendarDays size={14} /> JUN 3–7, 2027</span><span>5 DAYS · 4 NIGHTS</span></div></div><div className="trip-card-info"><div><p className="micro-label">NICE & MONACO, FRANCE / MONACO</p><h3>The Monaco weekend</h3><p>Big race energy. Your own pace.</p></div><div className="trip-price"><span>From</span><strong>$1,890</strong><small>/ person</small></div></div><div className="card-foot"><span>Stay your way <span>·</span> Race views optional <span>·</span> Good company</span><span>Explore the trip <ArrowRight size={14} /></span></div></a>
        <a className="trip-card" href="#/france"><div className="trip-image"><img src={ASSETS.france} alt="Warm stone architecture and relaxed life in the South of France" loading="lazy" /><Tag className="image-tag">THE SLOWER ROUTE</Tag><span className="round-arrow"><ArrowUpRight size={22} /></span><div className="image-bottom"><span><MapPin size={14} /> NICE → AVIGNON → PARIS</span><span>9 DAYS</span></div></div><div className="trip-card-info"><div><p className="micro-label">THREE CITIES. ONE VERY GOOD IDEA.</p><h3>A little more France</h3><p>Riviera mornings. Parisian evenings.</p></div><div className="trip-price"><span>From</span><strong>$3,495</strong><small>/ person</small></div></div><div className="card-foot"><span>6–14 travelers <span>·</span> Room to wander</span><span>Take a look <ArrowRight size={14} /></span></div></a>
      </div><p className="sample-note">A redesign concept using sample trip selections. No bookings or payments are made.</p></section>

      <section className="way-section" id="how-it-works"><div className="wrap"><div className="section-heading"><div><Eyebrow>LESS LOGISTICS. MORE LIVING.</Eyebrow><h2>We do the homework.<br /><em>You make the memories.</em></h2></div><p>All the ease of having a plan.<br />All the freedom of doing your own thing.</p></div><div className="steps-grid"><div className="step-card"><span className="step-number">01</span><div className="step-illustration route-illustration"><span className="tiny-place">NICE</span><div className="dotted-route" /><MapPin className="illustration-pin" size={30} /><span className="tiny-place end-place">SOMEWHERE GOOD</span></div><h3>Find your starting point.</h3><p>Choose a thoughtfully put-together trip. The route, lovely stays, and little details are already figured out.</p></div><div className="step-card"><span className="step-number">02</span><div className="step-illustration"><div className="mini-choice"><BedDouble size={17} /><span>A stay by the sea</span><span className="mini-check"><Check size={12} /></span></div><div className="mini-choice tilted"><Ship size={17} /><span>An afternoon afloat</span><Plus size={15} /></div></div><h3>Make it feel like you.</h3><p>Pick your stay, add an experience, leave an afternoon open. See exactly what changes as you choose.</p></div><div className="step-card"><span className="step-number">03</span><div className="step-illustration"><div className="mini-ticket"><span><Sun size={17} /> YOUR ONLY PLAN</span><strong>Have a really good day.</strong><span className="ticket-dashes" /></div></div><h3>Arrive. And exhale.</h3><p>Your itinerary, tickets, and people are in the app. We're a message away. The day is yours to enjoy.</p></div></div></div></section>

      <section className="app-promo wrap"><div className="app-promo-copy"><Eyebrow light>A LITTLE HELP IN YOUR POCKET</Eyebrow><h2>Less “where’s that ticket?”<br /><em>More “look at this.”</em></h2><p>Your next train. Your favorite people. That boat trip you decided to join. Your whole trip, in one calm little place.</p><Button href="#/app" className="button-white">Step inside the app <ArrowUpRight size={18} /></Button><div className="app-promo-features"><span><Check size={14} /> Your itinerary</span><span><Check size={14} /> Your people</span><span><Check size={14} /> Real support</span></div></div><div className="promo-phone-wrap"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="floating-note"><span>✦</span> A plan. Not a schedule.</div><MiniPhone /></div></section>

      <section className="story-section wrap" id="our-story"><div className="story-symbol">↗</div><Eyebrow>THE GUIDELESS WAY</Eyebrow><h2>Independent.<br /><em>Never on your own.</em></h2><p>We believe the best trips leave room for you. A little spontaneity. A shared table. An afternoon that goes nowhere in particular. We handle the complicated parts so you can find the good ones.</p><a className="text-link" href="#/trip">Find a trip that feels like you <ArrowUpRight size={17} /></a></section>
      <FAQ />
    </main><Footer navigate={navigate} />
  </>;
}

const faqs = [
  ['So, is there really no guide?', 'That’s right. You explore independently, with your itinerary, directions, tickets, and support in the app. We organize the important parts and leave the discovering to you.'],
  ['Can I come on my own?', 'Absolutely. Your own room is the default. Welcome drinks and optional group moments make it easy to meet people, with plenty of space to do your own thing.'],
  ['What’s included in my trip?', 'Your trip page spells it out. For the Monaco weekend, the base includes four nights, breakfast, a Nice–Monaco train pass, welcome drinks, and trip support. Race viewing, flights, and optional extras are separate.'],
  ['Can I add things later?', 'Yes. You can choose an experience before departure or during the trip, subject to availability. You will see the price and applicable terms before making a choice.'],
];
function FAQ() {
  const [open, setOpen] = useState(-1);
  return <section className="faq-section wrap"><div><Eyebrow>A FEW GOOD QUESTIONS</Eyebrow><h2>Glad you <em>asked.</em></h2><p>A little clarity before the adventure.</p></div><div className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${open === i ? 'expanded' : ''}`} key={q}><button aria-expanded={open === i} aria-controls={`faq-${i}`} onClick={() => setOpen(open === i ? -1 : i)}>{q}{open === i ? <Minus size={18} /> : <Plus size={18} />}</button>{open === i && <p id={`faq-${i}`}>{a}</p>}</div>)}</div></section>;
}
function Footer({ navigate }) {
  return <footer className="footer"><div className="wrap footer-top"><div><Brand light /><p>Go together.<br />Be guided by no one.</p></div><div className="footer-links"><a href="#/#trips" onClick={(e) => { e.preventDefault(); navigate('/', 'trips'); }}>Our trips</a><a href="#/#how-it-works" onClick={(e) => { e.preventDefault(); navigate('/', 'how-it-works'); }}>How it works</a><a href="#/app">Your trip app</a><a href="mailto:hello@guidelesstravel.com">Say hello <ArrowUpRight size={14} /></a></div><div className="footer-signoff"><span>LESS PLANNING.</span><strong>More <em>possibility.</em> ↗</strong></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Guideless redesign concept</span><span>Independent concept · Sample data · No live bookings</span><span>Made for the way you travel.</span></div></footer>;
}

function TripPage({ navigate, france = false }) {
  const [day, setDay] = useState(0);
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);
  const days = france ? [
    { label: 'Nice', title: 'A very good place to begin.', text: 'Settle into the Riviera rhythm. Find a café, wander the old town, and meet your fellow travelers over welcome drinks.', events: [['AFTERNOON', 'Arrive and settle in', 'Your hotel, your own room', BedDouble], ['EVENING', 'A first toast to France', 'Welcome drinks · Included', Coffee]] },
    { label: 'Avignon', title: 'Take the scenic route.', text: 'Trade sea air for warm stone streets. Discover Avignon with time for long lunches and a little aimless wandering.', events: [['MORNING', 'On to Provence', 'Intercity journey · Included', TrainFront], ['AFTERNOON', 'Follow your curiosity', 'Free time · Your choice', Compass]] },
    { label: 'Paris', title: 'Save a little room for Paris.', text: 'Neighborhood cafés, riverside walks, and one last evening together. Explore the city at your own pace.', events: [['MORNING', 'Bonjour, Paris', 'Travel and hotel · Included', TrainFront], ['EVENING', 'One more good evening', 'Optional group meetup', Users]] }
  ] : [
    { label: 'Thu, Jun 3', title: 'Hello, Riviera.', text: 'Land in Nice, settle into your hotel, and let the weekend begin. Meet a few new faces over a drink by the harbor. No agenda required.', events: [['AFTERNOON', 'Check in. Switch off.', 'Your selected hotel · Included', BedDouble], ['8:00 PM', 'A first round, together', 'Port Lympia · Welcome drinks included', Coffee]] },
    { label: 'Fri, Jun 4', title: 'The coast is calling.', text: 'A slow morning, a swim, or the optional coast boat to Monaco. Leave space for whatever catches your eye.', events: [['MORNING', 'An unhurried start', 'Breakfast at your hotel · Included', Coffee], ['10:00 AM', 'Take the coastal route', 'Boat to Monaco · Optional, $210/person', Ship]] },
    { label: 'Sat, Jun 5', title: 'Find your view.', text: 'Make your way to Monaco for qualifying, if included in your chosen race experience. There is a whole harbor to explore before the action.', events: [['MORNING', 'Nice to Monaco', 'Train pass · Included', TrainFront], ['AFTERNOON', 'Qualifying, your way', 'Selected race experience · Optional', Flag]] },
    { label: 'Sun, Jun 6', title: 'This is the moment.', text: 'The sound, the harbor, the anticipation. Experience race day from your chosen view, then swap stories with the group.', events: [['MORNING', 'Make your way to Monaco', 'Use your train pass or walk from your stay', TrainFront], ['AFTERNOON', 'The Monaco Grand Prix', 'Your selected race viewing · Optional', Flag]] },
    { label: 'Mon, Jun 7', title: 'Until the next one.', text: 'One last breakfast, a stroll if there is time, and the journey home. Take the memories. Leave the logistics to us.', events: [['MORNING', 'One more café au lait', 'Breakfast · Included', Coffee], ['BY 11:00 AM', 'Check out', 'Airport transfers available as an add-on', Luggage]] }
  ];
  const active = days[day] || days[0];
  return <><main className="trip-detail"><div className="wrap"><div className="breadcrumb"><a href="#/">Home</a><ChevronRight size={12} /><a href="#/#trips" onClick={(e) => { e.preventDefault(); navigate('/', 'trips'); }}>Our trips</a><ChevronRight size={12} /><span>{france ? 'Southern France' : 'Monaco Grand Prix'}</span></div><div className="detail-heading"><div><Eyebrow>{france ? 'THE SLOWER ROUTE · SOUTHERN FRANCE' : 'THE EVENT EDIT · JUNE 3–7, 2027'}</Eyebrow><h1>{france ? 'A little more ' : 'The Monaco '}<em>{france ? 'France.' : 'weekend.'}</em></h1><p>{france ? 'Riviera light. Provençal afternoons. Parisian evenings.' : 'The Riviera. The race. A weekend that’s entirely yours.'}</p></div><div className="detail-actions"><button className={`icon-button bordered ${saved ? 'saved' : ''}`} onClick={() => setSaved(!saved)} aria-label={saved ? 'Remove from saved trips' : 'Save this trip'} aria-pressed={saved}><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button><button className="icon-button bordered" aria-label="Copy trip link" onClick={async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 2500); } catch { setCopied(false); } }}>{copied ? <Check size={18} /> : <Copy size={18} />}</button>{copied && <span className="copy-note" role="status">Link copied</span>}</div></div><div className="detail-gallery"><img className="gallery-main" src={france ? ASSETS.france : ASSETS.monaco} alt={france ? 'A sunlit escape in France' : 'The Monaco coastline and harbor'} /><div className="gallery-side"><img src={ASSETS.hero} alt="Colorful waterfront on the French Riviera" /><div className="gallery-caption"><MapPin size={18} /><span>{france ? 'Nice → Avignon → Paris' : 'Nice & Monaco'}<small>A pretty good place to be.</small></span></div></div><Tag className="gallery-tag"><Users size={13} /> Independent, together</Tag></div><div className="trip-facts"><span><CalendarDays /><span>{france ? '9 days' : '5 days, 4 nights'}<small>Room to make it yours</small></span></span><span><MapPin /><span>{france ? 'Three French cities' : 'Nice & Monaco'}<small>{france ? 'One thoughtfully planned route' : 'One coast. Two ways to stay.'}</small></span></span><span><Users /><span>{france ? '6–14 travelers' : '12–50 travelers'}<small>Your own room by default</small></span></span><span><Compass /><span>Freedom included<small>No guide. No headcounts.</small></span></span></div>
      <div className="detail-columns"><div className="detail-main"><section className="detail-intro"><Eyebrow>THE GOOD PART STARTS HERE</Eyebrow><h2>{france ? 'France, with room ' : 'A big weekend.'}<br /><em>{france ? 'to get a little lost.' : 'Zero rigid plans.'}</em></h2><p>{france ? 'Start beside the Mediterranean, slow down in Provence, and finish with Paris. We handle the stays and journeys. You find the little places, long lunches, and unexpected favorites along the way.' : 'Four nights on the Riviera, with the most iconic weekend in racing on your doorstep. Stay in lively Nice or in the heart of Monaco. Choose a grandstand, a terrace, or simply soak up the atmosphere.'}</p><p>We organize the essentials and bring good people together. What you do with the rest? That’s the best part.</p></section><section className="included-section"><h3>A few things you can stop thinking about.</h3><div className="included-grid">{[[BedDouble, france ? 'Lovely stays in every city' : 'Four nights, breakfast included'], [TrainFront, france ? 'Journeys between cities' : 'Nice ↔ Monaco train pass'], [Coffee, 'Welcome drinks, on us'], [Smartphone, 'Your trip app & real support']].map(([Icon, text]) => <div key={text}><Icon size={20} /><span>{text}</span><Check size={14} /></div>)}</div><div className="excluded-note"><Info size={16} /><p>{france ? 'Flights, most meals, and optional experiences are extra.' : 'Race tickets, flights, most meals, and optional experiences are extra. Choose only what you want.'}</p></div></section>
      <section className="itinerary-section"><Eyebrow>A PLAN WITH ROOM TO WANDER</Eyebrow><h2>{france ? 'Three chapters.' : 'Your weekend,'} <em>{france ? 'All yours.' : 'loosely speaking.'}</em></h2><div className="day-tabs" role="tablist" aria-label="Trip itinerary">{days.map((item, i) => <button key={item.label} role="tab" aria-selected={day === i} aria-controls="day-panel" id={`day-tab-${i}`} onClick={() => setDay(i)} className={day === i ? 'active' : ''}><small>{france ? `CHAPTER 0${i + 1}` : `DAY 0${i + 1}`}</small>{item.label}</button>)}</div><div className="day-panel" role="tabpanel" id="day-panel" aria-labelledby={`day-tab-${day}`}><Tag>{france ? active.label : day === 0 || day === 4 ? 'NICE' : 'NICE & MONACO'}</Tag><h3>{active.title}</h3><p>{active.text}</p><div className="timeline">{active.events.map(([time, title, desc, Icon]) => <div className="timeline-row" key={title}><span className="timeline-icon"><Icon size={18} /></span><div><small>{time}</small><strong>{title}</strong><p>{desc}</p></div></div>)}</div><div className="free-time"><Sun size={17} /><span>Everything in between? Follow your curiosity.</span></div></div></section></div>
      <aside className="detail-booking"><Tag className="blue-tag">YOUR NEXT GOOD STORY</Tag><span className="booking-price-label">{france ? '9 days in France, from' : 'Your Monaco weekend, from'}</span><div className="big-price">{france ? '$3,495' : '$1,890'}<span>/ person</span></div><p>Own room. Essentials handled.</p><div className="booking-card-divider" /><div className="booking-fact"><CalendarDays size={18} /><div><strong>{france ? 'May departure · Sample itinerary' : 'June 3–7, 2027'}</strong><small>{france ? '9 days · 3 cities' : 'Thursday to Monday · 4 nights'}</small></div></div><div className="booking-fact"><BedDouble size={18} /><div><strong>Your own space</strong><small>Solo-friendly, always</small></div></div>{!france && <div className="booking-fact"><Ticket size={18} /><div><strong>Race viewing is optional</strong><small>Add the view that suits you</small></div></div>}<Button href={france ? '#/trip' : '#/build'}>{france ? 'Try the Monaco trip builder' : 'Make this trip yours'}<ArrowUpRight size={18} /></Button><span className="booking-small"><ShieldCheck size={14} />{france ? 'Explore our interactive demo' : '$500 base deposit per traveler'}</span><p className="booking-disclaimer">{france ? 'This route preview is illustrative. The interactive booking concept features Monaco.' : 'Extras paid upfront. See your full breakdown before continuing.'}</p></aside></div>
      </div><FAQ /></main><Footer navigate={navigate} /></>;
}

function PriceSummary({ trip, compact = false }) {
  const p = calculate(trip);
  return <div className={`price-summary ${compact ? 'compact' : ''}`}><div className="summary-trip"><img src={ASSETS.monaco} alt="Monaco harbor" /><div><span className="micro-label">YOUR WEEKEND</span><h3>Monaco, your way.</h3><p>Jun 3–7, 2027 · {trip.travelers} {trip.travelers === 1 ? 'traveler' : 'travelers'}</p></div></div><div className="summary-lines"><div><span>Base trip <small>{trip.travelers} × $1,890</small></span><strong>{money(p.base)}</strong></div>{p.stay > 0 && <div><span>Monaco stay upgrade</span><strong>{money(p.stay)}</strong></div>}{p.race > 0 && <div><span>{raceNames[trip.race]} <small>{trip.travelers} {trip.travelers === 1 ? 'ticket' : 'tickets'}</small></span><strong>{money(p.race)}</strong></div>}{p.boat > 0 && <div><span>Coast boat <small>{Math.min(trip.boatGuests, trip.travelers)} {trip.boatGuests === 1 ? 'traveler' : 'travelers'}</small></span><strong>{money(p.boat)}</strong></div>}{p.transfer > 0 && <div><span>Airport transfer <small>Per booking</small></span><strong>{money(p.transfer)}</strong></div>}</div><div className="summary-total"><span>Trip total <small>USD · {trip.travelers === 1 ? 'For one traveler' : `For ${trip.travelers} travelers`}</small></span><strong aria-live="polite">{money(p.total)}</strong></div><div className="payment-split"><div><span>Due today</span><strong>{money(p.today)}</strong></div><div><span>Remaining balance</span><strong>{money(p.later)}</strong></div><p>$500 deposit per traveler + selected extras today. Remaining trip balance before departure.</p></div><div className="summary-reassurance"><ShieldCheck size={17} /><span>Every choice, clearly priced.<br /><small>Flights not included. No payment in this demo.</small></span></div></div>;
}

function Builder({ trip, setTrip, navigate }) {
  const [step, setStep] = useState(0);
  const [summaryOpen, setSummaryOpen] = useState(false);
  const headings = [['Start with a little possibility.', 'One iconic weekend. How many of you are coming?'], ['Find your kind of home base.', 'The same great weekend. Two very different front doors.'], ['What’s your point of view?', 'Pick your race experience, or leave the decision for later.'], ['A little extra, if you like.', 'The best plans have room for a good last-minute idea.'], ['Looking like a good weekend.', 'A last look at the details. Every choice is still yours to change.']];
  const labels = ['Your trip', 'Your stay', 'Your view', 'Little extras', 'Review'];
  const update = (patch) => setTrip((prev) => ({ ...prev, ...patch }));
  const goStep = (n) => { setStep(n); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <main className="builder-page"><div className="wrap"><a className="back-link" href="#/trip"><ArrowLeft size={14} /> Back to the weekend</a><div className="builder-topline"><Eyebrow>MAKE IT YOURS</Eyebrow><span><CheckCheck size={14} /> Your choices are saved on this device</span></div><nav className="builder-steps" aria-label="Booking steps">{labels.map((label, i) => <button key={label} className={`${step === i ? 'current' : ''} ${step > i ? 'completed' : ''}`} onClick={() => goStep(i)} aria-current={step === i ? 'step' : undefined}><span>{step > i ? <Check size={14} /> : `0${i + 1}`}</span>{label}<ChevronRight size={14} /></button>)}</nav><div className="builder-layout"><section className="builder-main"><div className="builder-heading"><span className="micro-label">STEP 0{step + 1} OF 05</span><h1>{headings[step][0]}</h1><p>{headings[step][1]}</p></div>
        {step === 0 && <div className="builder-options"><div className="date-selection"><div><CalendarDays size={22} /><div><strong>June 3–7, 2027</strong><p>Thursday to Monday · 5 days, 4 nights</p></div></div><Tag className="blue-tag">MONACO GRAND PRIX</Tag><CircleCheck size={21} className="blue" /></div><div className="traveler-picker"><div><h3>Your travel people</h3><p>Coming solo? You’re in good company.</p></div><div className="stepper"><button aria-label="Remove a traveler" disabled={trip.travelers === 1} onClick={() => update({ travelers: trip.travelers - 1, boatGuests: Math.min(trip.boatGuests, trip.travelers - 1) })}><Minus size={17} /></button><span aria-live="polite">{trip.travelers}</span><button aria-label="Add a traveler" disabled={trip.travelers === 4} onClick={() => update({ travelers: trip.travelers + 1 })}><Plus size={17} /></button></div></div><div className="gentle-note"><BedDouble size={20} /><div><strong>Your own room. Your own rhythm.</strong><p>This demo includes one private room per traveler, for up to four travelers.</p></div></div><div className="included-preview"><h3>Already part of the plan</h3>{['Four nights with breakfast', 'Nice ↔ Monaco train pass, Friday–Sunday', 'Welcome drinks on Thursday', 'Your trip app, group access, and support'].map(t => <span key={t}><Check size={15} />{t}</span>)}</div></div>}
        {step === 1 && <div className="stay-options">{[{ id: 'nice', location: 'NICE · PORT QUARTER', title: 'A little Riviera rhythm.', desc: 'Old-town wanders, harbor cafés, and a lovely place to come back to.', image: ASSETS.nice, price: 'Included', features: ['Nice port area', '20–25 min train to Monaco', 'Private room · Breakfast included'] }, { id: 'monaco', location: 'MONACO · MONTE CARLO', title: 'Right in the middle of it.', desc: 'Wake up close to the action. Walk to the circuit. Make an evening of it.', image: ASSETS.monaco, price: '+$3,950', features: ['Monte Carlo location', 'Walk to the circuit', 'Private room · Breakfast included'] }].map(stay => <button className={`stay-card ${trip.stay === stay.id ? 'selected' : ''}`} key={stay.id} onClick={() => update({ stay: stay.id })} aria-pressed={trip.stay === stay.id}><div className="stay-photo"><img src={stay.image} alt={stay.id === 'nice' ? 'Riviera waterfront near Nice' : 'Monaco harbor and city, illustrating the destination'} /><span className="selection-circle">{trip.stay === stay.id && <Check size={14} />}</span>{stay.id === 'nice' && <Tag>THE GOOD-VALUE BASE</Tag>}</div><div className="stay-info"><span className="micro-label">{stay.location}</span><h3>{stay.title}</h3><p>{stay.desc}</p><div className="stay-features">{stay.features.map((f, i) => <span key={f}>{i === 0 ? <MapPin size={14} /> : i === 1 ? <TrainFront size={14} /> : <BedDouble size={14} />}{f}</span>)}</div><div className="stay-price"><strong>{stay.price}</strong><span>{stay.id === 'nice' ? 'in your base trip' : 'per traveler · 4 nights'}</span></div></div></button>)}<div className="gentle-note full-span"><Navigation size={19} /><p>{trip.stay === "nice" ? "Your race-day journey: use your included train pass to Monaco, then walk to your selected race view." : "Your race-day journey: walk from your Monaco base. Your train pass stays included for exploring Nice."}</p></div><div className="gentle-note full-span"><Info size={19} /><p>Destination photographs illustrate the two locations. These are sample stays, not confirmed properties.</p></div></div>}
        {step === 2 && <div className="race-options">{[{ id: 'grandstand', tag: 'THE CLASSIC', name: 'Grandstand K', desc: 'The swimming-pool section. The roar of the crowd. A proper race-weekend seat.', days: 'Saturday + Sunday', includes: 'Reserved grandstand seating', price: 1290, Icon: Flag }, { id: 'terrace', tag: 'A LITTLE ELEVATED', name: 'Harbour terrace', desc: 'An open view, a long lunch, and somewhere comfortable to take it all in.', days: 'Saturday + Sunday', includes: 'Lunch and open bar both days', price: 3490, Icon: Sun }, { id: 'yacht', tag: 'SOMETHING SPECIAL', name: 'Harbour yacht', desc: 'Race day on the water. Brunch, a bar, and Monaco from a different angle.', days: 'Sunday only', includes: 'Brunch and bar · Saturday not included', price: 5950, Icon: Ship }, { id: 'none', tag: 'KEEP IT OPEN', name: 'I’ll decide later', desc: 'Enjoy the Riviera. Add race viewing later, subject to availability.', days: 'No race ticket selected', includes: 'Your base trip is still all set', price: 0, Icon: Compass }].map(({ id, tag, name, desc, days, includes, price, Icon }) => <button className={`race-card ${trip.race === id ? 'selected' : ''}`} key={id} onClick={() => update({ race: id })} aria-pressed={trip.race === id}><span className="race-icon"><Icon size={23} /></span><div className="race-info"><span className="micro-label">{tag}</span><h3>{name}</h3><p>{desc}</p><div className="race-meta"><span><CalendarDays size={13} />{days}</span><span>{includes}</span></div></div><div className="race-price"><span className="selection-circle">{trip.race === id && <Check size={14} />}</span><strong>{price ? `+${money(price)}` : '$0'}</strong><small>{price ? 'per traveler' : 'added'}</small></div></button>)}</div>}
        {step === 3 && <div className="extras-options"><div className={`extra-card ${trip.boat ? 'selected' : ''}`}><img src={ASSETS.boat} alt="Blue Mediterranean water and a coastal escape" /><div className="extra-info"><span className="micro-label">FRIDAY · 10 AM–1 PM</span><h3>The scenic route to Monaco.</h3><p>A shared coast boat from Nice, with a swim stop near Cap Ferrat. Some journeys deserve to take a little longer.</p><div className="extra-bottom"><span><strong>$210</strong> / traveler</span><button className={`small-button ${trip.boat ? 'is-added' : ''}`} onClick={() => update({ boat: !trip.boat })}>{trip.boat ? <><Check size={15} /> Added</> : <><Plus size={15} /> Add to my trip</>}</button></div>{trip.boat && <div className="participant-picker"><label htmlFor="boat-guests">Who’s joining?</label><select id="boat-guests" value={Math.min(trip.boatGuests, trip.travelers)} onChange={e => update({ boatGuests: Number(e.target.value) })}>{Array.from({ length: trip.travelers }, (_, i) => <option key={i} value={i + 1}>{i + 1 === trip.travelers && trip.travelers > 1 ? `Everyone (${trip.travelers} travelers)` : `${i + 1} ${i === 0 ? 'traveler' : 'travelers'}`}</option>)}</select><small>{trip.boatGuests < trip.travelers ? 'The others keep a free morning. Same trip, different plans.' : 'Selected travelers will see this in their itinerary.'}</small></div>}</div></div><div className={`transfer-card ${trip.transfer ? 'selected' : ''}`}><span className="race-icon"><CarFront size={24} /></span><div><h3>A smooth arrival.</h3><p>Private transfer from Nice airport to your hotel.</p><span><strong>$120</strong> per booking · One-way</span></div><button className={`small-button ${trip.transfer ? 'is-added' : ''}`} onClick={() => update({ transfer: !trip.transfer })}>{trip.transfer ? <><Check size={15} /> Added</> : <><Plus size={15} /> Add</>}</button></div><div className="gentle-note"><Sparkles size={20} /><p>Nothing here is a must. You can add experiences later, subject to availability.</p></div></div>}
        {step === 4 && <div className="review-options"><div className="review-banner"><CircleCheck size={26} /><div><h3>One weekend. Made yours.</h3><p>Here’s how your Riviera escape is shaping up.</p></div></div>{[['Your people', `${trip.travelers} ${trip.travelers === 1 ? 'traveler' : 'travelers'} · Private rooms`, Users, 0], ['Your home base', trip.stay === 'nice' ? 'Nice, near the port · 4 nights' : 'Monte Carlo, Monaco · 4 nights', BedDouble, 1], ['Your race view', raceNames[trip.race], Flag, 2], ['Your little extras', [trip.boat ? `Coast boat for ${Math.min(trip.boatGuests, trip.travelers)}` : null, trip.transfer ? 'Airport transfer' : null].filter(Boolean).join(' · ') || 'Keeping things open', Sparkles, 3]].map(([label, value, Icon, index]) => <div className="review-row" key={label}><Icon size={21} /><div><small>{label}</small><strong>{value}</strong></div><button onClick={() => goStep(index)}>Edit <ArrowUpRight size={13} /></button></div>)}<div className="review-inclusions"><h3>The essentials come with you.</h3><p>Breakfast, your Friday–Sunday train pass, welcome drinks, group access, and trip support are included. Flights and most meals are separate.</p></div><div className="gentle-note"><Info size={19} /><p>This is an interactive design concept. Continue to preview your trip in the app. No reservation is created and no payment is taken.</p></div></div>}
        <div className="builder-navigation">{step > 0 ? <button className="back-link" onClick={() => goStep(step - 1)}><ArrowLeft size={16} /> Back</button> : <span className="quiet-label"><ShieldCheck size={15} /> No commitment. Just possibilities.</span>}<Button onClick={() => step < 4 ? goStep(step + 1) : navigate('/app')}>{step === 4 ? 'Preview my trip app' : `Next: ${labels[step + 1].toLowerCase()}`}<ArrowRight size={17} /></Button></div>
      </section><aside className="builder-sidebar"><PriceSummary trip={trip} /><div className="sidebar-note"><MessageCircle size={18} /><p>A question along the way?<br /><a href="mailto:hello@guidelesstravel.com">The Guideless team is here.</a></p></div></aside></div></div><div className="mobile-summary-bar"><button onClick={() => setSummaryOpen(true)}><span>YOUR TRIP TOTAL <ChevronDown size={12} /></span><strong>{money(calculate(trip).total)}</strong></button><Button onClick={() => step < 4 ? goStep(step + 1) : navigate('/app')}>{step === 4 ? 'Preview app' : 'Continue'}<ArrowRight size={16} /></Button></div>{summaryOpen && <Modal title="Your trip, clearly priced." onClose={() => setSummaryOpen(false)}><PriceSummary trip={trip} /></Modal>}</main>;
}

function MiniPhone() {
  return <div className="mini-phone"><div className="phone-island" /><div className="mini-phone-top"><span>9:41</span><span>●●● ▰</span></div><div className="mini-app-header"><Brand small /><span className="avatar">J</span></div><span className="micro-label">FRIDAY, JUNE 4 · NICE</span><h3>Bonjour, <em>you.</em> <Sun size={22} /></h3><p>A little sea air looks good on you.</p><div className="mini-phone-photo"><img src={ASSETS.nice} alt="A morning beside the sea in Nice" /><span><MapPin size={11} /> YOUR RIVIERA WEEKEND</span></div><div className="mini-next"><span className="micro-label">UP NEXT · 10:00 AM</span><h4>The scenic route to Monaco.</h4><span><Ship size={15} /> Coast boat · Port Lympia</span><div className="mini-app-button">Let’s get you there <ArrowUpRight size={13} /></div></div><div className="mini-phone-nav"><span className="active"><Sun size={17} />Today</span><span><Map size={17} />My trip</span><span><Users size={17} />People</span><span><MessageCircle size={17} />Support</span></div></div>;
}

function Modal({ title, children, onClose }) {
  const ref = useRef(null);
  useEffect(() => {
    const previous = document.activeElement;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    ref.current?.focus();
    const handle = (e) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'Tab') {
        const nodes = ref.current?.querySelectorAll('button, a[href], input, select, textarea, [tabindex="0"]');
        if (!nodes?.length) return;
        const first = nodes[0], last = nodes[nodes.length - 1];
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    };
    document.addEventListener('keydown', handle);
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener('keydown', handle); previous?.focus(); };
  }, [onClose]);
  return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onClick={e => e.stopPropagation()}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21} /></button></div>{children}</section></div>;
}

function Companion({ trip, setTrip }) {
  const [tab, setTab] = useState('today');
  const [modal, setModal] = useState(null);
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);
  const [guest, setGuest] = useState(1);
  const joinedBoat = trip.boat && guest <= trip.boatGuests;
  const [joinedDrinks, setJoinedDrinks] = useState(true);
  return <main className="companion-page"><div className="companion-layout wrap"><aside className="companion-intro"><Eyebrow>THE GUIDELESS COMPANION</Eyebrow><h1>Your whole trip.<br /><em>One happy place.</em></h1><p>The next adventure. The little details.<br />The people along for the ride.</p><div className="companion-side-card"><span className="micro-label">YOUR CURRENT TRIP</span><img src={ASSETS.monaco} alt="Monaco harbor" /><h3>The Monaco weekend</h3><span>June 3–7, 2027 · {trip.travelers} {trip.travelers === 1 ? 'traveler' : 'travelers'}</span><a href="#/build">Adjust your trip <ArrowUpRight size={15} /></a></div><div className="demo-hint"><Sparkles size={19} /><p>Take a look around. Your choices from the trip builder appear here.</p></div><p className="sample-note">Interactive app preview · Sample itinerary<br />No real tickets, bookings, or messages.</p></aside><div className="companion-device"><div className="device-status"><span>9:41</span><div className="device-island" /><span>●●● ▰</span></div><div className="companion-screen"><div className="companion-app-top"><Brand small /><button className="avatar" aria-label="View traveler profile" onClick={() => setModal('profile')}>J</button></div>
      {tab === 'today' && <div className="app-view"><div className="app-date"><span>FRIDAY, JUNE 4</span><span><Sun size={13} /> RIVIERA MORNINGS</span></div><h2>Bonjour, <em>you.</em><span>☀</span></h2><p className="app-greeting">A little sea air looks good on you.</p><div className="app-hero-photo"><img src={trip.stay === "nice" ? ASSETS.nice : ASSETS.monaco} alt={trip.stay === "nice" ? "The Nice promenade" : "Monaco harbor"} /><span><MapPin size={12} /> {trip.stay === 'nice' ? 'NICE, FRENCH RIVIERA' : 'MONTE CARLO, MONACO'}</span><div className="app-trip-day">DAY <strong>02</strong><span>OF 05</span></div></div><div className="app-section-title"><h3>Your day, at a glance</h3><button onClick={() => setTab('itinerary')}>Full itinerary <ArrowRight size={13} /></button></div><div className="app-next-card"><span className="micro-label">{joinedBoat ? 'UP NEXT · 10:00 AM' : 'THIS MORNING · YOUR OWN PACE'}</span><h3>{joinedBoat ? 'The scenic route to Monaco.' : 'A slow start. A good coffee.'}</h3><p>{joinedBoat ? 'A little coastline. A swim stop. A very good Friday.' : 'Breakfast is included. The rest of the morning is beautifully open.'}</p><div className="app-next-location">{joinedBoat ? <Ship size={18} /> : <Coffee size={18} />}<span>{joinedBoat ? 'Port Lympia, Nice' : trip.stay === 'nice' ? 'Your hotel in Nice' : 'Your hotel in Monte Carlo'}<small>{joinedBoat ? 'Meet 15 minutes before departure' : 'Breakfast at your own pace'}</small></span></div><button className="app-primary" onClick={() => setModal(joinedBoat ? 'directions' : 'hotel')}>{joinedBoat ? 'Meeting point & details' : 'Your stay details'}<ArrowUpRight size={15} /></button></div><div className="app-section-title"><h3>A little possibility</h3><Sparkles size={15} /></div><button className="app-experience" onClick={() => setModal('boat')}><img src={ASSETS.boat} alt="Blue water on the Riviera" /><div><Tag>{joinedBoat ? 'IN YOUR PLAN' : trip.boat ? 'IN YOUR GROUP’S PLAN' : 'OPTIONAL · TODAY'}</Tag><h4>A morning on the water.</h4><span>Coast boat to Monaco <ArrowUpRight size={14} /></span></div></button><div className="app-free-note"><Sun size={16} /><span>Leave a little room for the unexpected.</span></div></div>}
      {tab === 'itinerary' && <div className="app-view"><span className="micro-label">JUNE 3–7, 2027</span><h2>Your <em>weekend.</em></h2><p className="app-greeting">A plan with plenty of breathing room.</p><div className="app-ticket-shortcuts"><button onClick={() => setModal('ticket')}><Ticket size={20} />My tickets<ArrowUpRight size={13} /></button><button onClick={() => setModal('hotel')}><BedDouble size={20} />My stay<ArrowUpRight size={13} /></button></div>{[['THU', '03', 'Hello, Riviera.', ['Check into your hotel', '8 PM · Welcome drinks at Port Lympia']], ['FRI', '04', 'Follow the coastline.', [joinedBoat ? '10 AM · Coast boat to Monaco' : 'A free morning, just for you', 'Afternoon · Follow your curiosity']], ['SAT', '05', 'Find your view.', [trip.stay === 'nice' ? 'Train to Monaco · Pass included' : 'Walk to the circuit from your stay', trip.race === 'grandstand' || trip.race === 'terrace' ? `Qualifying · ${raceNames[trip.race]}` : 'Free afternoon · No qualifying ticket selected']], ['SUN', '06', 'The big day.', [trip.race === 'none' ? 'Race viewing not selected · Explore freely' : `Race day · ${raceNames[trip.race]}`, 'Optional · Harbour meetup']], ['MON', '07', 'Take the good memories.', ['Breakfast & check out by 11 AM', trip.transfer ? 'Return airport travel · Arrange separately' : 'Your onward journey']]].map(([day, date, title, events]) => <div className="app-day" key={date}><div className={`app-day-number ${date === '04' ? 'today' : ''}`}><span>{day}</span><strong>{date}</strong></div><div><h3>{title}</h3>{events.map(e => <p key={e}><span />{e}</p>)}</div></div>)}<p className="sample-note">Illustrative schedule. Check confirmed trip documents for final details.</p></div>}
      {tab === 'people' && <div className="app-view"><span className="micro-label">INDEPENDENT. TOGETHER.</span><h2>Your kind of <em>people.</em></h2><p className="app-greeting">A few familiar faces, wherever the day goes.</p><div className="people-banner"><div className="avatar-stack"><span>AL</span><span>SK</span><span>JM</span><span>+9</span></div><h3>Same weekend.<br />A dozen different stories.</h3><p>Sample group preview · 12 travelers</p></div><div className="app-section-title"><h3>A table with your name on it.</h3></div><div className="group-event"><Tag>OPTIONAL GROUP MOMENT</Tag><h3>One more drink by the harbor?</h3><p>Sunday evening · Port Hercule<br />An easy way to end a very good weekend.</p><button className="app-primary" onClick={() => setJoinedDrinks(!joinedDrinks)}>{joinedDrinks ? <><Check size={16} /> You’re interested</> : <>Count me in <Plus size={16} /></>}</button><small>Demo RSVP · Nothing is sent to a real group.</small></div><div className="gentle-note"><Users size={19} /><p>Join what feels good. Skip what doesn’t. That’s the whole idea.</p></div></div>}
      {tab === 'support' && <div className="app-view"><span className="micro-label">REAL PEOPLE. RIGHT HERE.</span><h2>A little <em>help?</em></h2><p className="app-greeting">We already know your trip. Start anywhere.</p><div className="support-person"><span className="avatar">G</span><div><strong>Your Guideless team</strong><span>Trip support · Demo conversation</span></div></div><div className="chat-bubble">Hi there! Need a hand finding your train, your meeting point, or your next good coffee? You’re in the right place.</div>{sent && <><div className="chat-bubble own">{message}</div><div className="chat-bubble">This is a preview of the support experience. Your message has not been sent. In the live app, the team would help with your itinerary.</div></>}<form className="support-form" onSubmit={(e) => { e.preventDefault(); if (message.trim()) setSent(true); }}><label htmlFor="support-message">Your message</label><textarea id="support-message" placeholder="A quick question about my trip…" value={message} onChange={e => { setMessage(e.target.value); setSent(false); }} required maxLength={500} /><button className="app-primary" type="submit">Preview a conversation <ArrowRight size={15} /></button></form><p className="sample-note">For real inquiries: <a href="mailto:hello@guidelesstravel.com">hello@guidelesstravel.com</a></p></div>}
      </div><nav className="app-bottom-nav" aria-label="Trip app navigation">{[['today', Sun, 'Today'], ['itinerary', Map, 'My trip'], ['people', Users, 'People'], ['support', MessageCircle, 'Support']].map(([id, Icon, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)} aria-current={tab === id ? 'page' : undefined}><Icon size={21} /><span>{label}</span></button>)}</nav><div className="device-home-indicator" /></div><div className="companion-side-note"><span>✳</span><p>A plan in your pocket.<br />The day in your hands.</p></div></div>
      {modal && <Modal title={({ boat: 'A morning on the water.', hotel: 'Your home base.', ticket: 'Your trip essentials.', directions: 'Meet by the water.', profile: 'Your travel people.' })[modal]} onClose={() => setModal(null)}>
        {modal === 'boat' && <div className="experience-modal"><img src={ASSETS.boat} alt="Mediterranean coastal water" /><Eyebrow>FRIDAY, JUNE 4 · 10 AM–1 PM</Eyebrow><p>A shared boat from Nice to Monaco, with a swim stop near Cap Ferrat. Meet at Port Lympia 15 minutes before departure.</p><div className="modal-feature-list"><span><Check size={15} /> Shared boat & skipper</span><span><Check size={15} /> Swim stop near Cap Ferrat</span><span><Check size={15} /> Return using your included train pass</span><span><Info size={15} /> Lunch and drinks are extra</span></div><div className="experience-price"><strong>$210 <small>/ traveler</small></strong><span>Sample add-on</span></div>{trip.travelers > 1 && <div className="participant-picker"><label htmlFor="app-boat-guests">How many travelers?</label><select id="app-boat-guests" value={trip.boatGuests} onChange={e => setTrip(t => ({ ...t, boatGuests: Number(e.target.value) }))}>{Array.from({ length: trip.travelers }, (_, i) => <option value={i + 1} key={i}>{i + 1} {i === 0 ? 'traveler' : 'travelers'}</option>)}</select></div>}<Button onClick={() => { setTrip(t => ({ ...t, boat: !t.boat })); setModal(null); }}>{trip.boat ? 'Remove from my sample trip' : 'Add to my sample trip'}{trip.boat ? <Minus size={16} /> : <Plus size={16} />}</Button><p className="sample-note">Updates your demo itinerary and trip total. No booking or charge.</p></div>}
        {modal === 'hotel' && <div className="hotel-modal"><img src={trip.stay === 'nice' ? ASSETS.nice : ASSETS.monaco} alt="Illustrative destination accommodation" /><Tag className="blue-tag">JUNE 3–7 · FOUR NIGHTS</Tag><h3>{trip.stay === 'nice' ? 'Nice, near the port.' : 'Monte Carlo, Monaco.'}</h3><p>{trip.stay === 'nice' ? 'A base near Port Lympia and the old town, with a train journey to Monaco.' : 'A base in Monte Carlo, within walking distance of the circuit.'}</p><div className="modal-feature-list"><span><BedDouble size={17} /> Private room per traveler</span><span><Coffee size={17} /> Breakfast included</span><span><Clock3 size={17} /> Check in Thursday · Check out Monday by 11 AM</span></div><div className="gentle-note"><Info size={18} /><p>Sample stay preview. The actual hotel name and address would appear after confirmation.</p></div></div>}
        {modal === 'ticket' && <div className="ticket-modal"><div className="demo-ticket"><TrainFront size={28} /><span className="micro-label">INCLUDED WITH YOUR TRIP</span><h3>Nice ↔ Monaco</h3><p>Regional train pass · Friday–Sunday</p><strong>DEMO · NOT VALID FOR TRAVEL</strong></div><div className="demo-ticket"><Flag size={28} /><span className="micro-label">YOUR RACE SELECTION</span><h3>{raceNames[trip.race]}</h3><p>{trip.race === 'none' ? 'No race ticket selected' : trip.race === 'yacht' ? 'Sunday only' : 'Saturday + Sunday'}</p><strong>{trip.race === 'none' ? 'ADD A VIEW IN THE TRIP BUILDER' : 'DEMO · NOT VALID FOR ENTRY'}</strong></div></div>}
        {modal === 'directions' && <div className="directions-modal"><div className="meeting-point"><MapPin size={35} /><span>PORT LYMPIA</span><h3>Nice, France</h3><p>Friday, June 4 · Arrive by 9:45 AM</p></div><p>Your exact boarding location and skipper’s contact would appear in your confirmed trip documents.</p><a className="button button-primary" href="https://www.google.com/maps/search/?api=1&query=Port+Lympia+Nice+France" target="_blank" rel="noreferrer">See Port Lympia on a map <ExternalLink size={16} /></a><p className="sample-note">General port location, not a confirmed boarding point.</p></div>}
        {modal === 'profile' && <div className="profile-modal"><p>Preview the itinerary for a traveler in your sample booking.</p><label htmlFor="active-guest">Viewing as</label><select id="active-guest" value={guest} onChange={e => setGuest(Number(e.target.value))}>{Array.from({ length: trip.travelers }, (_, i) => <option value={i + 1} key={i}>Traveler {i + 1}{i === 0 ? ' (you)' : ''}</option>)}</select><div className="gentle-note"><Info size={18} /><p>The boat activity appears for the number of travelers you selected. Other travelers keep a free morning.</p></div></div>}
      </Modal>}
    </main>;
}

function App() {
  const [route, setRoute] = useState(window.location.hash.replace('#', '').split('#')[0] || '/');
  const [trip, setTrip] = useState(loadTrip);
  useEffect(() => { try { localStorage.setItem('guideless-trip', JSON.stringify(trip)); } catch {} }, [trip]);
  useEffect(() => {
    const change = () => { const parts = window.location.hash.slice(1).split('#'); setRoute(parts[0] || '/'); if (parts[1]) setTimeout(() => document.getElementById(parts[1])?.scrollIntoView({ behavior: 'smooth' }), 80); else window.scrollTo(0, 0); };
    window.addEventListener('hashchange', change); change();
    return () => window.removeEventListener('hashchange', change);
  }, []);
  const navigate = (path, section) => { if (route === path && section) document.getElementById(section)?.scrollIntoView({ behavior: 'smooth' }); else window.location.hash = path + (section ? `#${section}` : ''); };
  useEffect(() => { document.title = ({ '/': 'Guideless — A little structure. A lot of freedom.', '/trip': 'The Monaco weekend — Guideless', '/france': 'A little more France — Guideless', '/approach': 'A design exploration for Guideless', '/build': 'Make Monaco yours — Guideless', '/app': 'Your trip companion — Guideless' })[route] || 'Guideless Travel'; }, [route]);
  return <><a className="skip-link" href="#main-content" onClick={e => { e.preventDefault(); document.getElementById('main-content')?.focus(); }}>Skip to content</a><Header route={route} navigate={navigate} /><div id="main-content" tabIndex={-1}>{route === '/approach' ? <Approach setTrip={setTrip} navigate={navigate} /> : route === '/trip' ? <TripPage navigate={navigate} /> : route === '/france' ? <TripPage navigate={navigate} france /> : route === '/build' ? <Builder trip={trip} setTrip={setTrip} navigate={navigate} /> : route === '/app' ? <Companion trip={trip} setTrip={setTrip} /> : <Home navigate={navigate} />}</div></>;
}

createRoot(document.getElementById('root')).render(<App />);
import './refinements.css';
